apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acp-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: agentic-commerce
finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mikewithoutthemechanics/retail-agentic-commerce.git
    targetRevision: main
    path: deploy/production/gitops/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: acp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
